import Head from "next/head";
import Hero from "../pages/hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CubaSon - Viene pronto con la mejor recarga a Cuba.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
      </main>
    </div>
  );
}
